# Model training & evaluation

In [1]:
import os
print(os.getcwd())

/Users/diba/Git/skincare-recommender-app/notebooks

In [ ]:
# retrieve INCI from HuggingFace
#inci_df = pd.read_json("hf://datasets/yavuzyilmaz/cosmetic-ingredients/ingredients.json")

# save data locally
#inci_df.to_csv("../data/raw/inci_df.csv", index=False)

In [37]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from utils.data_loaders import load_all_reviews_from_sephora, load_inci_data

sephora_reviews_df = load_all_reviews_from_sephora()

inci_df = load_inci_data()

ImportError: cannot import name 'load_inci_data' from 'utils.data_loaders' (/Users/diba/Git/skincare-recommender-app/utils/data_loaders.py)

# Investogating Sephora reviews

In [14]:
sephora_reviews_df.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color
0,P473671,Fragrance Discovery Set,6342.0,19-69,6320.0,3.6364,11.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342.0,19-69,3827.0,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P473662,Rainbow Bar Eau de Parfum,6342.0,19-69,3253.0,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P473660,Kasbah Eau de Parfum,6342.0,19-69,3018.0,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P473658,Purple Haze Eau de Parfum,6342.0,19-69,2691.0,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
sephora_reviews_df.describe()
#sephora_reviews_df.shape # (1102905, 42)

,brand_id,loves_count,rating,reviews,price_usd,value_price_usd,sale_price_usd,limited_edition,new,online_only,...,sephora_exclusive,child_count,child_max_price,child_min_price,Unnamed: 0,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count
count,8494.000000,8.494000e+03,1.102627e+06,8216.000000,1.102905e+06,451.000000,270.000000,8494.000000,8494.000000,8494.000000,...,8494.000000,8494.000000,2754.000000,2754.000000,1.094411e+06,926423.000000,532819.000000,1.094411e+06,1.094411e+06,1.094411e+06
mean,5422.440546,2.917957e+04,4.298378e+00,448.545521,4.902877e+01,91.168537,20.207889,0.070285,0.071698,0.219096,...,0.279374,1.631622,53.792023,39.665802,1.989864e+05,0.839962,0.767782,4.177126e+00,8.948695e-01,3.282257e+00
std,1709.595957,6.609212e+04,1.146057e+00,1101.982529,4.016662e+01,79.195631,24.327352,0.255642,0.258002,0.413658,...,0.448718,5.379470,58.765894,38.685720,1.749886e+05,0.366642,0.317164,2.271524e+01,5.288943e+00,1.967482e+01
min,1063.000000,0.000000e+00,1.000000e+00,1.000000,3.000000e+00,0.000000,1.750000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,3.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,5333.000000,3.758000e+03,4.000000e+00,26.000000,2.500000e+01,45.000000,8.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,22.000000,19.000000,5.590600e+04,1.000000,0.652174,0.000000e+00,0.000000e+00,0.000000e+00
50%,6157.500000,9.880000e+03,5.000000e+00,122.000000,3.900000e+01,67.000000,14.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,32.000000,28.000000,1.308240e+05,1.000000,0.928571,0.000000e+00,0.000000e+00,0.000000e+00
75%,6328.000000,2.684125e+04,5.000000e+00,418.000000,6.200000e+01,108.500000,25.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,59.000000,42.000000,3.285265e+05,1.000000,1.000000,3.000000e+00,1.000000e+00,3.000000e+00
max,8020.000000,1.401068e+06,5.000000e+00,21281.000000,1.900000e+03,617.000000,320.000000,1.000000,1.000000,1.000000,...,1.000000,105.000000,570.000000,400.000000,6.021290e+05,1.000000,1.000000,5.464000e+03,1.159000e+03,5.050000e+03

In [17]:
sephora_reviews_df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price', 'source_file', 'Unnamed: 0',
       'author_id', 'is_recommended', 'helpfulness', 'total_feedback_count',
       'total_neg_feedback_count', 'total_pos_feedback_count',
       'submission_time', 'review_text', 'review_title', 'skin_tone',
       'eye_color', 'skin_type', 'hair_color'],
      dtype='object')

In [ ]:
inci_df =

          ingredient                                        description
0           Glycerin  Glycerin doesnâ€™t sound very glamorous but it i...
1    Butylene Glycol  Butylene glycol, or letâ€™s just call it BG, is ...
2           Squalene  Squalene is an oily liquid that originally com...
3       Ceteareth-20  A common functional ingredient that helps to k...
4  Glyceryl Stearate  A super common, waxy, white, solid stuff that ...